### ISSUE TITLE
Design reference analysis

### ISSUE THREAD

**Issue by cipriancus** [cipriancus/CryMa#10]

**Comment by cocageorgiana** [comment]
https://www.w3schools.com/icons/fontawesome_icons_currency.asp
http://www.free-css.com/free-css-templates/page156/oodles
http://www.free-css.com/free-css-templates/page165/brainmix
https://developer.tizen.org/community/tip-tech/creating-complete-currency-calculator-application-angularjs-tizen-%E2%80%93-part-2
https://startbootstrap.com/template-overviews/sb-admin/
https://startbootstrap.com/template-overviews/sb-admin-2/
