### ISSUE TITLE
User interface mockup

### ISSUE THREAD

**Issue by cipriancus** [cipriancus/CryMa#22]

**Comment by cocageorgiana** [comment]
![bitcoindistribution](https://user-images.githubusercontent.com/12010069/32405252-a053533a-c16a-11e7-924c-36336fbef437.PNG)
![convert](https://user-images.githubusercontent.com/12010069/32405253-a078b6c0-c16a-11e7-88fa-86aeae8c9350.PNG)
![dailychart](https://user-images.githubusercontent.com/12010069/32405254-a09c1f7a-c16a-11e7-941d-b9b610ac3528.png)
![montlychart](https://user-images.githubusercontent.com/12010069/32405255-a0bcd620-c16a-11e7-82ff-daa81d6391fe.png)
![news1](https://user-images.githubusercontent.com/12010069/32405256-a0e08138-c16a-11e7-8eb5-0f150204f00e.PNG)
![news2](https://user-images.githubusercontent.com/12010069/32405257-a1015606-c16a-11e7-9917-37775bd83e72.PNG)
![piedistribution](https://user-images.githubusercontent.com/12010069/32405259-a1575d8a-c16a-11e7-8c88-479f271fcc70.PNG)


I created user interface template
