### ISSUE TITLE
Model RDF Entities

### ISSUE THREAD

**Issue by cipriancus** [cipriancus/CryMa#26]
We need to model what entity we use, how, and how they interact with each other

**Comment by AsoFC** [comment]
https://drive.google.com/drive/folders/0B_jRMRTB7_hgdGlWcHM3Z3k2N28

**Comment by AsoFC** [comment]
https://lh4.googleusercontent.com/sRgVm5t_jWOGBWQ3nq2Z4vDmU6GqAQpK6YPk_X6KjnTh8e7BUr5KF2Eb4QakKjWclPXzKLUscDC-234=w1922-h1096-rw
